name: Deploy Infrastructure

on: [push]

jobs:
  tf_deploy:
    defaults:
      run:
        working-directory: terraform/
    name: Deploy Services
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: "Setup - Build AWS Credentials"
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: GITHUB_OWNER=paulthiele1311 GITHUB_TOKEN=${{ secrets.GH_ACCESS_KEY }} terraform plan

      - name: Terraform Apply
        run: GITHUB_OWNER=paulthiele1311 GITHUB_TOKEN=${{ secrets.GH_ACCESS_KEY }} terraform apply -auto-approve
