name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up secret file
        env:
          TEST: ${{ secrets.TEST }}

        run: |
          echo ${{secrets.TEST}} | sed 's/./& /g'